export const phones = [
  {
    "id": 0,
    "brand": "Acer",
    "model": "Iconia Talk S",
    "network_technology": "GSM / HSPA / LTE",
    "2G_bands": "GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2",
    "3G_bands": "HSDPA 850 / 1900 / 2100",
    "4G_bands": "LTE band 1(2100)| 3(1800)| 7(2600)| 8(900)| 20(800)",
    "network_speed": "HSPA 42.2/11.5 Mbps  LTE Cat4 150/50 Mbps",
    "GPRS": "Yes",
    "EDGE": "Yes",
    "announced": "2016  August",
    "status": "Available. Released 2016  October",
    "dimentions": "191.7 x 101 x 9.4 mm (7.55 x 3.98 x 0.37 in)",
    "weight_g": 260,
    "weight_oz": 9.17,
    "SIM": "Dual SIM (Micro-SIM/Nano-SIM)",
    "display_type": "IPS LCD capacitive touchscreen  16M colors",
    "display_resolution": "7.0 inches (~69.8% screen-to-body ratio)",
    "display_size": "720 x 1280 pixels (~210 ppi pixel density)",
    "OS": "Android 6.0 (Marshmallow)",
    "CPU": "Quad-core 1.3 GHz Cortex-A53",
    "Chipset": "Mediatek MT8735",
    "GPU": "Mali-T720MP2",
    "memory_card": "microSD  up to 128 GB (dedicated slot)",
    "internal_memory": "16/32 GB",
    "RAM": "2 GB RAM",
    "primary_camera": "13 MP| autofocus",
    "secondary_camera": "2 MP| 720p",
    "loud_speaker": "Yes",
    "audio_jack": "Yes",
    "WLAN": "Wi-Fi 802.11 a/b/g/n| Wi-Fi Direct| hotspot",
    "bluetooth": "4.0| A2DP",
    "GPS": "Yes with A-GPS GLONASS",
    "NFC": "",
    "radio": "FM radio",
    "USB": "microUSB 2.0",
    "sensors": "Accelerometer| proximity",
    "battery": "Non-removable Li-Ion 3400 mAh battery (12.92 Wh)",
    "colors": "Black",
    "approx_price_EUR": 170,
    "img_url": "http://cdn2.gsmarena.com/vv/bigpic/acer-iconia-talk-s.jpg"
  },
  {
    "id": 1,
    "brand": "Acer",
    "model": "Liquid Z6 Plus",
    "network_technology": "GSM / HSPA / LTE",
    "2G_bands": "GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM model only)",
    "3G_bands": "HSDPA",
    "4G_bands": "LTE",
    "network_speed": "HSPA 42.2/5.76 Mbps  LTE Cat4 150/50 Mbps",
    "GPRS": "Yes",
    "EDGE": "Yes",
    "announced": "2016  August",
    "status": "Available. Released 2016  December",
    "dimentions": "153.8 x 75.6 x 8.5 mm (6.06 x 2.98 x 0.33 in)",
    "weight_g": 169,
    "weight_oz": 5.96,
    "SIM": "Single SIM (Micro-SIM) or Dual SIM (Micro-SIM| dual stand-by)",
    "display_type": "IPS LCD capacitive touchscreen  16M colors",
    "display_resolution": "5.5 inches (~71.7% screen-to-body ratio)",
    "display_size": "1080 x 1920 pixels (~401 ppi pixel density)",
    "OS": "Android 6.0 (Marshmallow)",
    "CPU": "Octa-core 1.3 GHz Cortex-A53",
    "Chipset": "Mediatek MT6753",
    "GPU": "Mali-T720MP3",
    "memory_card": "microSD  up to 256 GB (uses SIM 2 slot)",
    "internal_memory": "32 GB",
    "RAM": "3 GB RAM",
    "primary_camera": "13 MP| autofocus| LED flash",
    "secondary_camera": "5 MP",
    "loud_speaker": "Yes",
    "audio_jack": "Yes",
    "WLAN": "Wi-Fi 802.11 b/g/n| Wi-Fi Direct| hotspot",
    "bluetooth": "4.0| A2DP",
    "GPS": "Yes with A-GPS",
    "NFC": "",
    "radio": "FM radio",
    "USB": "microUSB 2.0",
    "sensors": "Fingerprint (front-mounted)| accelerometer| proximity",
    "battery": "Removable Li-Po 4080 mAh battery",
    "colors": "Black| White",
    "approx_price_EUR": 250,
    "img_url": "http://cdn2.gsmarena.com/vv/bigpic/acer-liquid-z6-plus.jpg"
  },
  {
    "id": 2,
    "brand": "Acer",
    "model": "Liquid Z6",
    "network_technology": "GSM / HSPA / LTE",
    "2G_bands": "GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM model only)",
    "3G_bands": "HSDPA",
    "4G_bands": "LTE",
    "network_speed": "HSPA  LTE",
    "GPRS": "Yes",
    "EDGE": "Yes",
    "announced": "2016  August",
    "status": "Available. Released 2016  December",
    "dimentions": "-",
    "weight_g": "",
    "weight_oz": "",
    "SIM": "Single SIM (Micro-SIM) or Dual SIM (Micro-SIM| dual stand-by)",
    "display_type": "IPS LCD capacitive touchscreen  16M colors",
    "display_resolution": "5.0 inches",
    "display_size": "720 x 1280 pixels (~294 ppi pixel density)",
    "OS": "Android 6.0 (Marshmallow)",
    "CPU": "Quad-core 1.25 GHz Cortex-A53",
    "Chipset": "Mediatek MT6737",
    "GPU": "Mali-T720MP2",
    "memory_card": "microSD  up to 256 GB",
    "internal_memory": "8 GB",
    "RAM": "1 GB RAM",
    "primary_camera": "8 MP| autofocus| LED flash",
    "secondary_camera": "2 MP",
    "loud_speaker": "Yes",
    "audio_jack": "Yes",
    "WLAN": "Yes",
    "bluetooth": "Yes",
    "GPS": "Yes with A-GPS",
    "NFC": "",
    "radio": "FM radio",
    "USB": "microUSB 2.0",
    "sensors": "Accelerometer| proximity",
    "battery": "Removable Li-Ion 2000 mAh battery",
    "colors": "Black| White",
    "approx_price_EUR": 120,
    "img_url": "http://cdn2.gsmarena.com/vv/bigpic/acer-liquid-z6.jpg"
  }
]